# Generation sequencer (mono-card NN=1, LUT-lean) over ss_link (LINK_SS).
SIM           ?= icarus
TOPLEVEL_LANG ?= verilog
RTL := $(abspath ../../src)

VERILOG_SOURCES += $(abspath ../models/Gowin_rPLL.v)
VERILOG_SOURCES += $(abspath ../models/MULTALU18X18.v)
VERILOG_SOURCES += $(abspath ../models/sdram_chip.v)
VERILOG_SOURCES += $(RTL)/mac18.v
VERILOG_SOURCES += $(RTL)/rmsnorm_op.v
VERILOG_SOURCES += $(RTL)/silu_op.v
VERILOG_SOURCES += $(RTL)/rope_op.v
VERILOG_SOURCES += $(RTL)/softmax_op.v
VERILOG_SOURCES += $(RTL)/attention_head_op.v
VERILOG_SOURCES += $(RTL)/sdram.v
VERILOG_SOURCES += $(abspath async_fifo.v)
VERILOG_SOURCES += $(abspath uart_bridge.v)
VERILOG_SOURCES += $(abspath vec_alu2.v)
VERILOG_SOURCES += $(RTL)/top.v
VERILOG_SOURCES += $(abspath gen_seq.v)
VERILOG_SOURCES += $(abspath gen_seq_top.v)

COMPILE_ARGS += -DLINK_SS
COMPILE_ARGS += -I$(RTL)

TOPLEVEL := gen_seq_top
MODULE   ?= test_gen_A

# copy LUT *.hex into cwd first (rmsnorm/silu $readmemh relative path)
include $(shell cocotb-config --makefiles)/Makefile.sim
